name: Go

on:
  push:
    branches: ["feature/yml"]

jobs:
  #build:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v4
  #  - uses: actions/setup-go@v5
  #  - name: Build
  #    run: go build -v ./...

  tests:
    #needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
    - name: Test
      run: go test -v ./...

  #tests-race:
  #  needs: build
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v4
  #  - uses: actions/setup-go@v5
  #  - name: Test
  #    run: go test -race -v ./...

  #lint:
  #  needs: [tests, tests-race]
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #    - uses: actions/setup-go@v5
  #    - uses: golangci/golangci-lint-action@v6

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: yurj9999/gogogo

      - name: Build and push Docker Inage
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }} 
